name: Setup Node.js and PNPM

runs:
  using: 'composite'
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: '10.9.0'
        run_install: false
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    
    - name: Install dependencies
      shell: bash
      run: pnpm install --global turbo@2.5 && pnpm install